enable: "ENABLE"

imu_data: "IMU_DATA" #LCM_LOCOMOTION_URL
odometry: "ODOMETRY" #LCM_LOCOMOTION_URL
contact_state: "CONTACT_SENSOR" #LCM_LOCOMOTION_URL 

robot_cmd: "ROBOT_CMD" #LCM_LOCOMOTION_URL
mpc_cmd: "MPC_CMD" #LCM_LOCOMOTION_URL
wbc_cmd: "WBC_CMD" #LCM_LOCOMOTION_URL
servo_cmd: "SERVO_CMD" #LCM_SERVO_URL

robot_state: "ROBOT_STATE" #LCM_LOCOMOTION_URL
robot_state_check: "ROBOT_STATE_CHECK" #LCM_LOCOMOTION_URL
wbc_state: "WBC_STATE" #LCM_LOCOMOTION_URL
servo_state: "SERVO_STATE" #LCM_SERVO_URL

gait_phase: "GAIT_PHASE" #LCM_LOCOMOTION_URL
gait_params: "GAIT_PARAMS" #LCM_LOCOMOTION_URL
footstep_sequence: "FOOTSTEP_SEQUENCE" #LCM_LOCOMOTION_URL
dcm_com_trajectory: "DCM_COM_TRAJECTORY" #LCM_LOCOMOTION_URL

depth_image: "DEPTH_IMAGE" #LCM_LOCOMOTION_URL
pointcloud: "POINCLOUD" #LCM_LOCOMOTION_URL
heightmap: "HEIGHTMAP" #LCM_LOCOMOTION_URL
