robot_config:
  # HARDWARE

  # ---------------------------------
  # best params for vision: 
  #   - t_sw = 0.19
  #   - t_st = 0.45
  #   - body_height = 0.2
  #   - stride_height = 0.353-0.362
  #   - dz_near_ground = -0.1
  #   - interleave_y: [0.08, 0.08, 0.08, 0.08]
  #   - ROBOT_BODY_Z = 0.21 
  # ---------------------------------

  # SIMULATION
  g: 9.81

  # leg params
  m1: 0.309
  m2: 0.532
  m3: 0.067

  l1: 0.0595
  l2: 0.13
  l3: 0.1485

  d1: 0.02
  d2: 0.086
  d3: 0.012

  Pc1: [0.05, 0.0, 0.0]
  Pc2: [0.01, 0.0, 0.04]
  Pc3: [0.06, 0.0, 0.01]

  # body params
  bx: 0.106
  by: 0.067

  M: 8.2 
  I_b: [[ 0.012838176, -0.000006851,  0.000156493],
        [-0.000006851,  0.056852389, -0.000095392],
        [ 0.000156493, -0.000095392,  0.064034355]]

  # motor params
  tau_max: [6.0, 6.0, 12.0]
  vel_max: [28.0, 28.0, 14.0]
  gear_ratio: 10.0
  kt: 0.74

  debug_mode: True

emergency:
  max_angles: [1.3, 2.6, 3.95, 
               1.3, 2.6,  3.95,
               1.3, 2.6, 3.95,
               1.3, 2.6,  3.95]

  min_angles: [-1.3, -2.6,  -3.95,
               -1.3, -2.6, -3.95,
               -1.3, -2.6,  -3.95,
               -1.3, -2.6, -3.95]
